version: '3'
services:
  # Deploy front-end on nginx image
  nginx:
    image: nginx:latest
    # container : machine
    ports:
      - '80:80'
    volumes:
      # 映射nginx.conf文件到容器的/etc/nginx/conf.d目录并覆盖default.conf文件
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # dist -> /usr/share/nginx/html
      - ./dist:/usr/share/nginx/html
    # 覆盖容器启动后默认执行的命令。
    command: /bin/bash -c "nginx -g 'daemon off;'"
